# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KEEP FIGOFUTURE's G.A.N.G.S.T.A.
email: figofuture@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  When in doubt, use brute force.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://figofuture.github.io" # the base hostname & protocol for your site
twitter_username: figofuture
github_username:  figofuture

# Build settings
markdown: kramdown
